version: "3.8"

services:
  lumen-app:
    build: ./lumen-api/lumen-app
    container_name: lumen-app
    restart: unless-stopped
    working_dir: /var/www
    env_file:
      - ./lumen-api/lumen-app/.env
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - "8000:8000"
    command: sh -c "php artisan migrate:fresh --seed --force && php -S 0.0.0.0:8000 -t public"

  node-cache:
    build: ./node-cache
    container_name: node-cache
    restart: unless-stopped
    working_dir: /usr/src/app
    env_file:
      - ./node-cache/.env
    ports:
      - "5000:5000"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    command: npm start

  frontend:
    build: ./frontend/energeXAI-Frontend
    container_name: frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - lumen-app

  mysql:
    image: mysql:8
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: energeX
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:6
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  # -------------------
  # Test Services
  # -------------------
  lumen-tests:
    build:
      context: ./lumen-api/lumen-app
      target: test   # 👈 uses the "test" stage from Dockerfile
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    working_dir: /var/www
    env_file:
      - ./lumen-api/lumen-app/.env.testing
    command: ["./vendor/bin/phpunit", "--testdox"]

  node-tests:
    build:
      context: ./node-cache
      target: test   # 👈 uses the "test" stage from Dockerfile
    working_dir: /usr/src/app
    env_file:
      - ./node-cache/.env
    depends_on:
      lumen-app:
        condition: service_started
    command: sh -c "sleep 10 && npm test"

volumes:
  dbdata:
